/* Builds webgl3d/bundle-3d.js: the 3D renderer as one classic script, for the game opened from disk
   (file://), where ES modules cannot load. No dependencies: Three.js (vendor/three.module.js) ends with
   a single `export { … }`, and the renderer modules only use plain `import … from` lines and
   `export function`, so they are joined into one function scope and the export list becomes an object.
   The bundle defines window.Board3D = { createThreeGameRenderer }.
   Run after changing webgl3d/*.js:  npm run build:3d   (tests/bundle-3d.test.js checks it is current). */
"use strict";
const fs = require("fs"),
	path = require("path");

const ROOT = path.join(__dirname, ".."),
	OUT = path.join(ROOT, "webgl3d", "bundle-3d.js"),
	// Dependency order: each module only uses the ones before it.
	MODULES = ["sky-3d.js", "night-lights-3d.js", "models-detail-3d.js", "nature-detail-3d.js", "props-detail-3d.js", "swarm-detail-3d.js", "act3-detail-3d.js", "act2-detail-3d.js", "act1-detail-3d.js", "models-3d.js", "weather-3d.js", "scene-fx-3d.js", "scene-life-3d.js", "scatter-3d.js", "objectives-3d.js", "marks-3d.js", "relief-3d.js", "three-renderer.js", "three-game-renderer.js"];

function threeAsObject(source) {
	const at = source.lastIndexOf("\nexport {") + 1,
		statements = source.match(/^(export|import)\s/gm) || [];
	if (at <= 0 || statements.length !== 1) throw Error("three.module.js: expected one export list at the end and no imports");
	const list = source.slice(at + "export {".length, source.indexOf("}", at)),
		entries = list
			.split(",")
			.map((s) => s.trim())
			.filter(Boolean)
			.map((s) => {
				const [local, exported = local] = s.split(/\s+as\s+/);
				return `${exported}: ${local}`;
			});
	return source.slice(0, at) + `const THREE = Object.freeze({ ${entries.join(", ")} });\n`;
}

function moduleBody(file, source) {
	const lines = source.split("\n"),
		out = [];
	for (const line of lines) {
		if (/^import\s/.test(line)) {
			if (!/^import .* from "[^"]+";\s*$/.test(line)) throw Error(`${file}: unsupported import: ${line}`);
			continue;
		}
		if (/^export\s/.test(line) && !/^export function /.test(line)) throw Error(`${file}: unsupported export: ${line}`);
		out.push(line.replace(/^export function /, "function "));
	}
	return out.join("\n");
}

function build() {
	const three = threeAsObject(fs.readFileSync(path.join(ROOT, "vendor", "three.module.js"), "utf8")),
		parts = MODULES.map((m) => `// ---- webgl3d/${m} ----\n` + moduleBody(m, fs.readFileSync(path.join(ROOT, "webgl3d", m), "utf8")));
	return [
		"/* GENERATED by tools/build-3d.js from vendor/three.module.js and webgl3d/*.js — do not edit; run npm run build:3d. */",
		"(function () {",
		'"use strict";',
		"// ---- vendor/three.module.js (Three.js 0.170.0, MIT) ----",
		three,
		...parts,
		"window.Board3D = { createThreeGameRenderer };",
		"})();",
		"",
	].join("\n");
}

if (require.main === module) {
	fs.writeFileSync(OUT, build());
	console.log(`${path.relative(ROOT, OUT)}: ${fs.statSync(OUT).size} B`);
}
module.exports = { build, OUT };
